baseURL: https://sylvie-zheng.netlify.app/
languageCode: en-us
title: Portfolio website for Yiwei (Sylvie) Zheng
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Currently, I'm looking for business analyst/data scientist full-time jobs. Also, I'm passionate about transforming business by technology, devoting myself in women in business and women in tech!
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Yiwei (Sylvie) Zheng, welcome to my personal website!
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: szheng.mam2023@london.edu
    enable: yes
    phone:
      - phone: (86) 13758209493
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Sylvie
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com/kostisc
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/yiwei.zheng.98229/
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com/kostisc
      - icon: fa-github
        label: GitHub
        url: https://github.com/sylvie-zheng
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/yiwei-sylvie-zheng/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: backround_sunset.jpg
        subtitle: I love sunsets
        title: About me
        url: blogs/risk_return
      - image: lbs
        subtitle: London Business School
        title: My school
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs